name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.4

  # Supabase
  supabase_flutter: ^2.3.0

  # UI Components
  cached_network_image: ^3.2.3
  timeago: ^3.2.0
  intl: ^0.19.0
  flutter_svg: ^2.0.6
  google_fonts: ^6.1.0

  # Utils
  uuid: ^4.3.3
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
